In [1]:
import pandas as pd
df = pd.read_csv('/content/amazon_prime_data.csv')
df.head()

,user_id,name,email_address,username,date_of_birth,gender,location,membership_start_date,membership_end_date,subscription_plan,payment_information,renewal_status,usage_frequency,purchase_history,favorite_genres,devices_used,engagement_metrics,feedback_ratings,customer_support_interactions
0,1,Ronald Murphy,williamholland@example.com,williamholland,1953-06-03,Male,Rebeccachester,2024-01-15,2025-01-14,Annual,Mastercard,Manual,Regular,Electronics,Documentary,Smart TV,Medium,3.6,3
1,2,Scott Allen,scott22@example.org,scott22,1978-07-08,Male,Mcphersonview,2024-01-07,2025-01-06,Monthly,Visa,Manual,Regular,Electronics,Horror,Smartphone,Medium,3.8,7
2,3,Jonathan Parrish,brooke16@example.org,brooke16,1994-12-06,Female,Youngfort,2024-04-13,2025-04-13,Monthly,Mastercard,Manual,Regular,Books,Comedy,Smart TV,Low,3.3,8
3,4,Megan Williams,elizabeth31@example.net,elizabeth31,1964-12-22,Female,Feliciashire,2024-01-24,2025-01-23,Monthly,Amex,Auto-renew,Regular,Electronics,Documentary,Smart TV,High,3.3,7
4,5,Kathryn Brown,pattersonalexandra@example.org,pattersonalexandra,1961-06-04,Male,Port Deborah,2024-02-14,2025-02-13,Annual,Visa,Auto-renew,Frequent,Clothing,Drama,Smart TV,Low,4.3,1

In [2]:
df.dtypes

user_id                            int64
name                              object
email_address                     object
username                          object
date_of_birth                     object
gender                            object
location                          object
membership_start_date             object
membership_end_date               object
subscription_plan                 object
payment_information               object
renewal_status                    object
usage_frequency                   object
purchase_history                  object
favorite_genres                   object
devices_used                      object
engagement_metrics                object
feedback_ratings                 float64
customer_support_interactions      int64
dtype: object

In [3]:
df.isnull().sum()

user_id                          0
name                             0
email_address                    0
username                         0
date_of_birth                    0
gender                           0
location                         0
membership_start_date            0
membership_end_date              0
subscription_plan                0
payment_information              0
renewal_status                   0
usage_frequency                  0
purchase_history                 0
favorite_genres                  0
devices_used                     0
engagement_metrics               0
feedback_ratings                 0
customer_support_interactions    0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

1. Retrieve the names and email addresses of all users.

In [5]:
df[['name', 'email_address']].sort_values(by = 'name').reset_index(drop = True)

                 name                email_address
0       Aaron Goodman  michaelanderson@example.org
1        Aaron Guzman   dawnwilliamson@example.org
2        Aaron Wilson          afisher@example.com
3       Abigail Boone          dsnyder@example.com
4     Abigail Carroll            bking@example.org
...               ...                          ...
2495    Zachary Mccoy      sanchezerin@example.net
2496  Zachary Sanders     aguilarlaura@example.net
2497    Zachary Simon           mlogan@example.org
2498    Zachary Smith   heathershields@example.org
2499  Zachary Vasquez    danielaguirre@example.org

[2500 rows x 2 columns]

2. Find the number of users by gender.

In [6]:
df['gender'].value_counts()

gender
Male      1260
Female    1240
Name: count, dtype: int64

In [7]:
df.groupby('gender').size()

gender
Female    1240
Male      1260
dtype: int64

3. Get the usernames and membership start dates of users who joined before a certain date (2024-03-13).

In [8]:
df.loc[(df['membership_start_date'] < '2024-03-13')][['username', 'membership_start_date']].sort_values(by = 'membership_start_date').reset_index(drop = True)

            username membership_start_date
0          kellylane            2024-01-01
1          carolyn16            2024-01-01
2     karenrodriguez            2024-01-01
3      michaellarson            2024-01-01
4      jamescaldwell            2024-01-01
...              ...                   ...
1703        mmullins            2024-03-12
1704      hoodmonica            2024-03-12
1705   elizabethkhan            2024-03-12
1706      laurasmith            2024-03-12
1707   christopher07            2024-03-12

[1708 rows x 2 columns]

In [9]:
df.query('membership_start_date < "2024-03-13"')[['username', 'membership_start_date']].sort_values(by = 'membership_start_date').reset_index(drop = True)

            username membership_start_date
0          kellylane            2024-01-01
1          carolyn16            2024-01-01
2     karenrodriguez            2024-01-01
3      michaellarson            2024-01-01
4      jamescaldwell            2024-01-01
...              ...                   ...
1703        mmullins            2024-03-12
1704      hoodmonica            2024-03-12
1705   elizabethkhan            2024-03-12
1706      laurasmith            2024-03-12
1707   christopher07            2024-03-12

[1708 rows x 2 columns]

4. Count the number of users from a specific location (let's say, locations that contains Port).

In [10]:
df.loc[df['location'].str.contains('Port')].groupby('location')['user_id'].count().sort_values(ascending=False)

location
Port John              3
Port Jonathan          3
Port Amanda            2
Port Angela            2
Port David             2
                      ..
Port Tylerbury         1
Port Wanda             1
Port William           1
Port Williehaven       1
Port Zacharyborough    1
Name: user_id, Length: 160, dtype: int64

In [11]:
df.query("location.str.contains('Port')", engine='python').groupby('location')['user_id'].count().sort_values(ascending=False)

location
Port John              3
Port Jonathan          3
Port Amanda            2
Port Angela            2
Port David             2
                      ..
Port Tylerbury         1
Port Wanda             1
Port William           1
Port Williehaven       1
Port Zacharyborough    1
Name: user_id, Length: 160, dtype: int64

5. List the subscription plans along with the count of users subscribed to each plan.

In [12]:
df['subscription_plan'].value_counts()

subscription_plan
Annual     1271
Monthly    1229
Name: count, dtype: int64

In [13]:
df.groupby('subscription_plan').size()

subscription_plan
Annual     1271
Monthly    1229
dtype: int64

6. Find the usernames and their corresponding payment information.

In [14]:
df[['username', 'payment_information']].sort_values(by = 'username').reset_index(drop = True)

         username payment_information
0       aanderson          Mastercard
1         aaron27                Visa
2         aaron29          Mastercard
3         aaron39                Visa
4         aaron70          Mastercard
...           ...                 ...
2495      zwalker          Mastercard
2496  zwashington                Amex
2497    zwilliams                Amex
2498      zwilson                Visa
2499      zwilson                Amex

[2500 rows x 2 columns]

In [20]:
grouped = df.groupby('username')['payment_information'].agg(lambda x: list(x) if len(x.unique()) > 1 else x.iloc[0]).reset_index()

result = grouped.sort_values(by='username').reset_index(drop=True)

result

          username payment_information
0        aanderson          Mastercard
1          aaron27                Visa
2          aaron29          Mastercard
3          aaron39                Visa
4          aaron70          Mastercard
...            ...                 ...
2453  zunigashelly          Mastercard
2454       zwalker          Mastercard
2455   zwashington                Amex
2456     zwilliams                Amex
2457       zwilson        [Visa, Amex]

[2458 rows x 2 columns]

7. Identify the renewal status of each user's subscription.

In [21]:
df[['username', 'renewal_status']].sort_values(by='renewal_status').reset_index(drop = True)

             username renewal_status
0         martinisaac     Auto-renew
1          powersmary     Auto-renew
2     jenniferroberts     Auto-renew
3      russellantonio     Auto-renew
4           jonbrooks     Auto-renew
...               ...            ...
2495          ejensen         Manual
2496       jodihanson         Manual
2497            prose         Manual
2498       wilcoxkara         Manual
2499   jasonrasmussen         Manual

[2500 rows x 2 columns]

8. Calculate the average usage frequency of all users.

In [22]:
df.usage_frequency.value_counts()

usage_frequency
Frequent      851
Regular       827
Occasional    822
Name: count, dtype: int64

In [23]:
usage_frequency_mapping = {
    'Frequent': 3,
    'Regular': 2,
    'Occasional': 1
}

df['usage_frequency_numeric'] = df['usage_frequency'].map(usage_frequency_mapping)

average_usage_frequency = round(df['usage_frequency_numeric'].mean(), 2)

average_usage_frequency

np.float64(2.01)

9. Determine the number of users with a specific purchase history (Clothing).

In [24]:
len(df.loc[df['purchase_history'] == 'Clothing'])

802

In [25]:
df.query('purchase_history == "Clothing"')['user_id'].count()

np.int64(802)

10. List the favorite genres of users along with the count of users for each genre.

In [26]:
df.favorite_genres.value_counts()

favorite_genres
Horror         383
Action         380
Romance        368
Drama          361
Comedy         349
Documentary    340
Sci-Fi         319
Name: count, dtype: int64

In [27]:
df.groupby('favorite_genres').size().sort_values(ascending = False)

favorite_genres
Horror         383
Action         380
Romance        368
Drama          361
Comedy         349
Documentary    340
Sci-Fi         319
dtype: int64

In [28]:
df.groupby('favorite_genres')['user_id'].count().sort_values(ascending = False)

favorite_genres
Horror         383
Action         380
Romance        368
Drama          361
Comedy         349
Documentary    340
Sci-Fi         319
Name: user_id, dtype: int64

11. Retrieve the distinct devices used by users.

In [29]:
list(df.devices_used.unique())

['Smart TV', 'Smartphone', 'Tablet']

12. Get the engagement metrics for users who gave feedback or ratings.

In [30]:
df.loc[df['feedback_ratings'].notna()][['user_id', 'engagement_metrics', 'feedback_ratings']].sort_values(by = 'feedback_ratings', ascending = True).reset_index(drop = True)

      user_id engagement_metrics  feedback_ratings
0        1882               High               3.0
1          28             Medium               3.0
2        2130                Low               3.0
3        2441                Low               3.0
4         554             Medium               3.0
...       ...                ...               ...
2495      821                Low               5.0
2496      883               High               5.0
2497      907                Low               5.0
2498      885             Medium               5.0
2499     2484               High               5.0

[2500 rows x 3 columns]

13. Find the usernames of users who had customer support interactions.

In [31]:
df.loc[df['customer_support_interactions'] != 0][['username', 'customer_support_interactions']].sort_values(by = 'customer_support_interactions', ascending = True).reset_index(drop = True)

          username  customer_support_interactions
0     jasonparsons                              1
1      smithgerald                              1
2     brandonlewis                              1
3           ujones                              1
4        theresa58                              1
...            ...                            ...
2257      pcamacho                             10
2258       apowell                             10
2259       ogarcia                             10
2260    juanmoreno                             10
2261  jamesedwards                             10

[2262 rows x 2 columns]

14. Identify the users who have memberships ending within a certain date range (in February 2025).

In [32]:
df.loc[(df.membership_end_date >= '2025-02-01') & (df.membership_end_date < '2025-03-01')][['username', 'membership_start_date', 'membership_end_date']].sort_values(by = 'membership_end_date').reset_index(drop = True)

          username membership_start_date membership_end_date
0       timothyday            2024-02-02          2025-02-01
1    robertsamanda            2024-02-02          2025-02-01
2     gardnerdonna            2024-02-02          2025-02-01
3           phicks            2024-02-02          2025-02-01
4           yjones            2024-02-02          2025-02-01
..             ...                   ...                 ...
628        smurray            2024-02-29          2025-02-28
629    brendasmith            2024-02-29          2025-02-28
630  chapmandonald            2024-02-29          2025-02-28
631        wwilson            2024-02-29          2025-02-28
632      nichole85            2024-02-29          2025-02-28

[633 rows x 3 columns]

15. List the users who have used a specific device (Tablet).

In [34]:
grouped = df.groupby('username')['devices_used'].agg(lambda x: list(set(x)) if len(x.unique()) > 1 else x.iloc[0]).reset_index()

grouped['device_count'] = grouped['devices_used'].apply(lambda x: len(x) if isinstance(x, list) else 1)

result = grouped.sort_values(by='device_count', ascending=False).reset_index(drop=True)

result

                username                    devices_used  device_count
0                scott11  [Smartphone, Smart TV, Tablet]             3
1              gwilliams            [Smartphone, Tablet]             2
2           jacqueline84            [Smartphone, Tablet]             2
3              panderson          [Smartphone, Smart TV]             2
4                david32              [Smart TV, Tablet]             2
...                  ...                             ...           ...
2453        hartmanaaron                          Tablet             1
2454      harveymargaret                          Tablet             1
2455       hawkinsedward                      Smartphone             1
2456            hayden35                      Smartphone             1
2457  harringtonnicholas                      Smartphone             1

[2458 rows x 3 columns]

In [35]:
df.loc[df['devices_used'] == 'Tablet']

,user_id,name,email_address,username,date_of_birth,gender,location,membership_start_date,membership_end_date,subscription_plan,payment_information,renewal_status,usage_frequency,purchase_history,favorite_genres,devices_used,engagement_metrics,feedback_ratings,customer_support_interactions,usage_frequency_numeric
5,6,Sandra Cox,gparks@example.org,gparks,1954-09-19,Female,Lake Johnathan,2024-01-15,2025-01-14,Monthly,Amex,Manual,Occasional,Books,Action,Tablet,Low,3.8,2,1
6,7,Benjamin Marshall,michaellewis@example.net,michaellewis,2003-02-09,Male,Carlsonchester,2024-04-08,2025-04-08,Monthly,Amex,Auto-renew,Frequent,Clothing,Sci-Fi,Tablet,Medium,4.4,10,3
9,10,Kayla Hernandez,jessica53@example.net,jessica53,1963-06-16,Male,West Stephen,2024-03-10,2025-03-10,Monthly,Visa,Auto-renew,Frequent,Clothing,Drama,Tablet,High,4.9,6,3
12,13,Kevin Mayo,hochoa@example.net,hochoa,1981-11-18,Female,Michaeltown,2024-01-10,2025-01-09,Monthly,Amex,Auto-renew,Regular,Clothing,Action,Tablet,Medium,4.7,0,2
13,14,Gregory Thomas,egriffin@example.com,egriffin,1989-08-17,Female,Harrisport,2024-01-07,2025-01-06,Annual,Amex,Auto-renew,Frequent,Books,Horror,Tablet,Medium,3.8,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2481,2482,Katie Gamble,denisejones@example.net,denisejones,1965-04-05,Female,Kevintown,2024-02-12,2025-02-11,Monthly,Visa,Auto-renew,Frequent,Clothing,Documentary,Tablet,Low,3.6,4,3
2483,2484,Samantha Lee,catherinecannon@example.com,catherinecannon,1960-09-23,Female,Edwardstown,2024-02-07,2025-02-06,Annual,Visa,Auto-renew,Occasional,Clothing,Sci-Fi,Tablet,High,5.0,2,1
2487,2488,Anthony Cruz,bradleycordova@example.org,bradleycordova,1973-03-04,Female,Gibsonstad,2024-04-08,2025-04-08,Monthly,Amex,Auto-renew,Regular,Clothing,Romance,Tablet,Low,4.4,2,2
2491,2492,Brian Robertson,jirwin@example.org,jirwin,1982-02-25,Female,Port Cheryltown,2024-02-25,2025-02-24,Monthly,Visa,Auto-renew,Occasional,Electronics,Action,Tablet,High,4.1,4,1
2497,2498,Morgan Barnes,erikaholland@example.net,erikaholland,1972-03-31,Female,Alexandraborough,2024-02-09,2025-02-08,Annual,Visa,Manual,Frequent,Electronics,Documentary,Tablet,Low,4.9,8,3

16. Calculate the total feedback or ratings given by users.

In [36]:
df.groupby('username')['feedback_ratings'].sum().sort_values(ascending = False)

username
scott11          13.1
ewilson          13.0
djohnson         11.7
jeremy97          9.8
bbell             9.7
                 ...
delgadokayla      3.0
bespinoza         3.0
dconway           3.0
zlee              3.0
abigailconrad     3.0
Name: feedback_ratings, Length: 2458, dtype: float64

17. Get the usernames of users who have renewed their subscription.

In [37]:
df[(df['renewal_status'] == 'Auto-renew')]['username'].reset_index(drop = True)

0              elizabeth31
1       pattersonalexandra
2             michaellewis
3                jessica53
4                   hochoa
               ...
1269                jirwin
1270            virginia02
1271     andersonchristina
1272       williamsroberto
1273           martinisaac
Name: username, Length: 1274, dtype: object

18. Find the usernames of users who have not made any purchases.

In [38]:
df[df['purchase_history'].isnull()]['username']

Series([], Name: username, dtype: object)

19. Identify the most frequently used device among users.

In [39]:
df['devices_used'].value_counts().idxmax()

'Smartphone'

20. List the usernames and their corresponding locations for users who are highly engaged.

In [40]:
df.loc[df['engagement_metrics'].str.lower() == 'high'][['username', 'location']].reset_index(drop = True)

           username           location
0       elizabeth31       Feliciashire
1         jessica53       West Stephen
2         phumphrey        New Brandon
3          ronald82       North Audrey
4     castillokatie       West Raymond
..              ...                ...
840  guzmanmichelle         Garzaburgh
841          jirwin    Port Cheryltown
842      virginia02  North Tinaborough
843    reedcourtney       Williammouth
844     martinisaac     Estradaborough

[845 rows x 2 columns]